const { chromium } = require('playwright');
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const browserTemp = path.join(root, '.runtime', 'browser-temp');
fs.mkdirSync(browserTemp, { recursive: true });
process.env.TEMP = browserTemp;
process.env.TMP = browserTemp;
const php = process.env.PIXEL_QA_PHP;
if (!php) throw new Error('Set PIXEL_QA_PHP to the portable PHP executable.');
const args = ['-d', `extension_dir=${path.join(path.dirname(php), 'ext')}`, '-d', 'extension=gd', '-d', 'extension=exif', '-d', 'extension=mbstring', '-d', 'extension=pdo_sqlite', '-d', 'extension=mysqli', '-d', 'memory_limit=512M'];
const auth = JSON.parse(execFileSync(php, [...args, path.join(__dirname, 'auth.php')], { encoding: 'utf8' }));
const results = [];
let browser;
const record = (test, passed, detail = '') => results.push({ test, status: passed ? 'PASS' : 'FAIL', detail });
(async () => {
    browser = await chromium.launch({ headless: true, channel: 'chrome' });
    const context = await browser.newContext();
    await context.addCookies(auth.cookies.map(cookie => ({ ...cookie, url: 'http://127.0.0.1:8877', httpOnly: true, sameSite: 'Lax' })));
    const page = await context.newPage();
    const errors = [];
    const external = [];
    page.on('pageerror', error => errors.push(error.message));
    await context.route('**/*', route => {
        if (new URL(route.request().url()).hostname !== '127.0.0.1') {
            external.push(new URL(route.request().url()).hostname);
            return route.abort();
        }
        return route.continue();
    });
    await page.goto('http://127.0.0.1:8877/wp-admin/upload.php?page=wp-seed-pixel');
    await page.locator('#pixel-start').waitFor();
    await page.locator('#pixel-preset').selectOption('balanced');
    record('Balanced intent selectable without technical quality entry', await page.locator('#pixel-preset').inputValue() === 'balanced');
    await page.locator('.wp-seed-pixel details').first().evaluate(el => { el.open = true; });
    for (const width of [1440, 820, 390, 320]) {
        await page.setViewportSize({ width, height: 1000 });
        const metrics = await page.evaluate(() => ({ overflow: document.documentElement.scrollWidth > window.innerWidth, labelled: [...document.querySelectorAll('.wp-seed-pixel input:not([type="hidden"]):not([type="submit"]),.wp-seed-pixel select')].every(el => el.labels.length > 0) }));
        record(`Admin ${width} no overflow`, !metrics.overflow);
        record(`Admin ${width} fields labelled`, metrics.labelled);
        await page.screenshot({ path: path.join(root, 'reports/final', `admin-${width}.png`), fullPage: true });
    }
    await page.locator('#pixel-start').focus();
    const outline = await page.locator('#pixel-start').evaluate(el => ({ width: getComputedStyle(el).outlineWidth, style: getComputedStyle(el).outlineStyle }));
    record('Keyboard focus indicator', outline.width !== '0px' && outline.style !== 'none');
    await page.keyboard.press('Tab');
    record('Keyboard Tab reaches next command', await page.locator('#pixel-pause').evaluate(el => el === document.activeElement));
    record('Progress has accessible label', await page.locator('#pixel-progress').evaluate(el => el.labels.length > 0));
    record('Live status uses text, not HTML', await page.locator('#pixel-result').getAttribute('aria-live') === 'polite');
    const ajax = async (body, anonymous = false, method = 'POST') => {
        const request = anonymous ? await browser.newContext() : context;
        const response = await request.request.fetch('http://127.0.0.1:8877/wp-admin/admin-ajax.php', { method, form: { action: 'wp_seed_pixel', nonce: auth.nonce, ...body } });
        const data = { status: response.status(), text: await response.text() };
        if (anonymous) await request.close();
        return data;
    };
    record('Anonymous mutation denied', (await ajax({ operation: 'start', preset: 'web', confirmed: '1' }, true)).status >= 400);
    record('Wrong nonce denied', (await ajax({ operation: 'status', nonce: 'invalid' })).status === 403);
    record('GET mutation denied', (await ajax({ operation: 'start', preset: 'web', confirmed: '1' }, false, 'GET')).status >= 400);
    record('Unknown operation rejected', (await ajax({ operation: 'evil' })).status === 400);
    record('Array injection rejected', (await ajax({ operation: 'optimize', 'attachment_id[]': '1', preset: 'web' })).status >= 400);
    for (const role of ['subscriber', 'author']) {
        const identity = JSON.parse(execFileSync(php, [...args, path.join(__dirname, 'auth.php'), role], { encoding: 'utf8' }));
        const lowPrivilege = await browser.newContext();
        await lowPrivilege.addCookies(identity.cookies.map(cookie => ({ ...cookie, url: 'http://127.0.0.1:8877', httpOnly: true, sameSite: 'Lax' })));
        const response = await lowPrivilege.request.post('http://127.0.0.1:8877/wp-admin/admin-ajax.php', { form: { action: 'wp_seed_pixel', nonce: identity.nonce, operation: 'start', preset: 'web', confirmed: '1' } });
        record(`${role} with valid nonce cannot start library batch`, response.status() === 403 && (await response.json()).data.message.includes('Permission'));
        await lowPrivilege.close();
        identity.cookies.forEach(cookie => { cookie.value = ''; });
        identity.nonce = '';
    }
    await page.goto('http://127.0.0.1:8877/wp-admin/upload.php?mode=list&s=Synthetic%20rgb.jpg');
    const regenerate = page.locator('.pixel-regenerate').first();
    const rowStatus = regenerate.locator('..').locator('.pixel-media-status');
    const attachmentId = await regenerate.getAttribute('data-id');
    await regenerate.focus();
    const actionResponse = page.waitForResponse(response => response.url().includes('admin-ajax.php') && (response.request().postData() || '').includes('operation=optimize'));
    await page.keyboard.press('Enter');
    const actionData = await (await actionResponse).json();
    if (!actionData.success) throw new Error('Media action failed: ' + actionData.data.code);
    await rowStatus.filter({ hasText: 'success' }).waitFor({ timeout: 30000, state: 'attached' });
    record('Media row regeneration works from keyboard', true);
    record('Media action restores keyboard focus', await regenerate.evaluate(el => el === document.activeElement));
    const statusMetrics = await rowStatus.evaluate(el => ({ text: el.textContent, fontSize: getComputedStyle(el).fontSize, rects: [...el.getClientRects()].map(r => ({ width: r.width, height: r.height })) }));
    record('Media action status is visible', statusMetrics.text.includes('success') && statusMetrics.rects.some(r => r.width > 0 && r.height > 0), JSON.stringify(statusMetrics));
    await page.screenshot({ path: path.join(root, 'reports/final', 'media-action-320.png'), fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.screenshot({ path: path.join(root, 'reports/final', 'media-action-1440.png'), fullPage: true });
    const nojs = await browser.newContext({ javaScriptEnabled: false });
    await nojs.addCookies(auth.cookies.map(cookie => ({ ...cookie, url: 'http://127.0.0.1:8877', httpOnly: true, sameSite: 'Lax' })));
    const nojsPage = await nojs.newPage();
    await nojsPage.goto('http://127.0.0.1:8877/wp-admin/upload.php?page=wp-seed-pixel');
    await nojsPage.locator('#pixel-id').fill(attachmentId);
    await nojsPage.locator('#pixel-single button').click();
    await nojsPage.waitForURL('**pixel_status=success');
    record('Native manual POST works without JavaScript', true);
    await nojs.close();
    await page.goto('http://127.0.0.1:8877/');
    const html = await page.content();
    record('No frontend plugin assets', !html.includes('/wp-seed-pixel/assets/'));
    record('No JavaScript errors', errors.length === 0, errors.join('; '));
    record('No plugin external requests', external.every(host => host === 'secure.gravatar.com'), external.length ? 'WordPress core Gravatar request observed and blocked; not a Pixel request.' : '');
    await page.goto('http://127.0.0.1:8877/wp-admin/upload.php?page=wp-seed-pixel');
    await page.setViewportSize({ width: 720, height: 500 });
    record('200 percent equivalent viewport has no overflow', await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
    await page.emulateMedia({ reducedMotion: 'reduce' });
    record('Reduced motion retains controls', await page.locator('#pixel-start').isVisible());
    await browser.close();
    auth.cookies.forEach(cookie => { cookie.value = ''; });
    auth.nonce = '';
    fs.writeFileSync(path.join(root, 'reports/final/browser-results.json'), JSON.stringify({ tests: results }, null, 2));
    const failed = results.filter(row => row.status === 'FAIL');
    console.log(JSON.stringify({ tests: results.length, pass: results.length - failed.length, failed }, null, 2));
    process.exitCode = failed.length ? 1 : 0;
})().catch(async error => { if (browser) await browser.close(); console.error(error.message); process.exitCode = 1; });
