<?php
require __DIR__ . '/format-bootstrap.php';
$checks = array();
function secure_ok($v, $name) { global $checks; if (!$v) { throw new RuntimeException($name); } $checks[$name] = true; }
$id = format_fixture(); $before = WP_Seed_Pixel_Master_Adapter::snapshot($id);
wp_set_current_user(0);
secure_ok(is_wp_error(WP_Seed_Pixel_Format_Conversion::analyze($id)), 'anonymous cannot analyze');
secure_ok(is_wp_error(WP_Seed_Pixel_Format_Conversion::record($id)), 'anonymous cannot read private recovery');
$user = wp_insert_user(array('user_login' => 'format-author-' . bin2hex(random_bytes(5)), 'user_pass' => bin2hex(random_bytes(24)), 'role' => 'author'));
wp_set_current_user($user);
secure_ok(is_wp_error(WP_Seed_Pixel_Format_Conversion::analyze($id)), 'non-admin cannot convert');
wp_set_current_user(1);
$a = WP_Seed_Pixel_Format_Conversion::analyze($id);
secure_ok(!is_wp_error($a), 'admin analysis');
secure_ok(is_wp_error(WP_Seed_Pixel_Format_Conversion::convert($id, str_repeat('a', 32), true)), 'stale generation cannot convert');
secure_ok(is_wp_error(WP_Seed_Pixel_Format_Conversion::resume($id, $a['generation'])), 'unapproved job cannot resume conversion');
$source = get_attached_file($id, true); $mode = fileperms($source) & 0777;
chmod($source, 0600);
secure_ok(is_wp_error(WP_Seed_Pixel_Format_Conversion::convert($id, $a['generation'], true)), 'changed source permissions block publication');
secure_ok(get_post_mime_type($id) === 'image/png', 'permission divergence preserves PNG authority');
chmod($source, $mode);
$bundle = WP_Seed_Pixel_Format_Conversion::record($id);
$native = array_values(array_diff(array_keys($bundle['record']['before']['files']), array($bundle['record']['before']['relative'])))[0];
$native_path = wp_upload_dir(null, false)['basedir'] . '/' . $native; $native_mode = fileperms($native_path) & 0777;
chmod($native_path, 0600);
secure_ok(is_wp_error(WP_Seed_Pixel_Format_Conversion::convert($id, $a['generation'], true)), 'changed derivative permissions block publication');
chmod($native_path, $native_mode);
$b = WP_Seed_Pixel_Format_Conversion::record($id); $candidate = $b['directory'] . '/new-master.jpg';
rename($candidate, $candidate . '.safe');
symlink(get_attached_file($id), $candidate);
secure_ok(is_wp_error(WP_Seed_Pixel_Format_Conversion::convert($id, $a['generation'], true)), 'private symlink cannot publish');
secure_ok(WP_Seed_Pixel_Master_Adapter::snapshot($id) === $before, 'symlink attack preserves PNG');
unlink($candidate); rename($candidate . '.safe', $candidate);
$mutator = static function ($meta) { $meta['file'] = '../escape.jpg'; return $meta; };
add_filter('wp_update_attachment_metadata', $mutator);
secure_ok(is_wp_error(WP_Seed_Pixel_Format_Conversion::convert($id, $a['generation'], true)), 'hostile metadata filter blocked');
secure_ok(get_post_mime_type($id) === 'image/png', 'metadata failure leaves PNG authoritative');
remove_filter('wp_update_attachment_metadata', $mutator);
$resume = WP_Seed_Pixel_Format_Conversion::resume($id, $a['generation']);
secure_ok(!is_wp_error($resume), 'approved interrupted publication resumes');
$path = get_attached_file($id, true); $sha = hash_file('sha256', $path);
$mode = fileperms($path) & 0777; chmod($path, 0600);
$view = WP_Seed_Pixel_Format_Conversion::record($id);
secure_ok(!WP_Seed_Pixel_Format_Conversion::view($view['item'], $view['record'], $view['directory'])['restore_available'], 'changed JPEG permissions disable restore');
secure_ok(is_wp_error(WP_Seed_Pixel_Format_Conversion::purge($id, $a['generation'], true, true)), 'changed JPEG permissions block purge');
chmod($path, $mode);
rename($path, $path . '.safe'); copy($path . '.safe', $path);
$view = WP_Seed_Pixel_Format_Conversion::record($id);
$v = WP_Seed_Pixel_Format_Conversion::view($view['item'], $view['record'], $view['directory']);
secure_ok(!$v['restore_available'], 'same bytes foreign inode does not offer restore');
secure_ok(is_wp_error(WP_Seed_Pixel_Format_Conversion::purge($id, $a['generation'], true, true)), 'foreign inode blocks purge');
secure_ok(is_file($path) && hash_file('sha256', $path) === $sha, 'foreign file never deleted');
unlink($path); rename($path . '.safe', $path);
link($path, $path . '.third');
secure_ok(is_wp_error(WP_Seed_Pixel_Format_Conversion::restore($id, $a['generation'])), 'extra hardlink blocks restore');
unlink($path . '.third');
secure_ok(!is_wp_error(WP_Seed_Pixel_Format_Conversion::restore($id, $a['generation'])), 'restoration succeeds after exact identity recovered');
$id2 = format_fixture(); $a2 = WP_Seed_Pixel_Format_Conversion::analyze($id2);
wp_update_post(array('ID' => $id2, 'post_status' => 'trash'));
secure_ok(is_wp_error(WP_Seed_Pixel_Format_Conversion::convert($id2, $a2['generation'], true)), 'trashed attachment cannot migrate');
$dir = getenv('PIXEL_FORMAT_REPORT_DIR') ?: '/mnt/c/Dev/git-worktrees/wp-seed-pixel-png-jpeg-explicit-conversion/reports/png-jpeg';
file_put_contents($dir . '/security-' . ($argv[1] ?? 'dev') . '.json', wp_json_encode(array('checks' => $checks, 'count' => count($checks)), JSON_PRETTY_PRINT));
echo count($checks) . " security checks PASS\n";
