const {chromium} = require('playwright');
const fs = require('fs');
const path = require('path');
const assert = require('node:assert/strict');
(async () => {
    const root = path.resolve(__dirname, '..');
    const state = JSON.parse(fs.readFileSync(path.join(root, '.runtime/format-browser.json')));
    const out = process.env.PIXEL_FORMAT_REPORT_DIR || path.join(root, 'reports/png-jpeg');
    const browser = await chromium.launch({headless: true, executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'});
    const errors = [], checks = {};
    try {
        const ctx = await browser.newContext({viewport: {width: 1440, height: 1000}});
        await ctx.addCookies(state.cookies);
        const page = await ctx.newPage();
        page.on('pageerror', e => errors.push(e.message));
        await page.goto(`http://127.0.0.1:8877/wp-admin/post.php?post=${state.id}&action=edit`);
        const panel = () => page.locator('.pixel-media-panel');
        await panel().locator('[data-operation="analyze"]').click();
        await panel().locator('.pixel-format-comparison').waitFor();
        checks.explicitAnalysis = true;
        assert.equal(await panel().locator('[data-format-profile]').count(), 3);
        assert.ok(await panel().locator('[data-format-profile]:enabled').count() >= 2);
        checks.measuredProfileRadios = true;
        await panel().locator('[data-format-profile="best"]').focus();
        await page.keyboard.press('Space');
        await page.waitForFunction(() => document.querySelector('[data-format-profile="best"]:checked') && document.querySelector('.pixel-media-panel').getAttribute('aria-busy') !== 'true');
        assert.equal(await panel().locator('[data-format-approval="confirmed"]').isChecked(), false);
        assert.match(await panel().innerText(), /Meilleure qualité/);
        checks.keyboardProfileChoice = true;
        await page.reload();
        assert.equal(await panel().locator('[data-format-profile="best"]').isChecked(), true);
        checks.selectedProfileReload = true;
        const bad = await ctx.request.post('http://127.0.0.1:8877/wp-admin/admin-ajax.php', {form: {action: 'wp_seed_pixel_format', operation: 'convert', attachment_id: state.id}});
        assert.equal(bad.status(), 403); checks.nonceMandatory = true;
        const convert = () => panel().locator('[data-operation="convert"]');
        assert.equal(await convert().isDisabled(), true);
        const summary = panel().locator('.pixel-format-comparison > summary');
        await summary.focus(); await page.keyboard.press('Enter');
        await page.waitForFunction(() => [...document.querySelectorAll('.pixel-format-comparison img')].every(i => i.complete && i.naturalWidth > 0));
        checks.authenticatedComparison = true;
        const anon = await browser.newContext();
        const preview = await anon.request.get(await panel().locator('img').first().getAttribute('src'));
        assert.equal(preview.status(), 400); checks.noAnonymousPreview = true;
        await anon.close();
        checks.keyboardComparison = true;
        for (const width of [1440, 820, 390, 320]) {
            await page.setViewportSize({width, height: 1000});
            await panel().scrollIntoViewIfNeeded();
            const overflow = await panel().evaluate(p => p.scrollWidth > p.clientWidth + 2);
            assert.equal(overflow, false); checks['width' + width] = true;
            await panel().screenshot({path: path.join(out, `comparison-${width}.png`)});
        }
        await page.setViewportSize({width: 1440, height: 2200});
        await page.evaluate(() => document.body.style.zoom = '2');
        await panel().evaluate(p => p.scrollIntoView({block: 'start'}));
        await page.evaluate(() => window.scrollBy(0, -100));
        assert.equal(await panel().evaluate(p => p.scrollWidth > p.clientWidth + 2), false);
        await panel().screenshot({path: path.join(out, 'comparison-zoom200.png')});
        checks.zoom200 = true;
        await page.evaluate(() => document.body.style.zoom = '');
        await panel().locator('[data-format-approval="confirmed"]').check();
        assert.equal(await convert().isDisabled(), true);
        await panel().locator('[data-format-approval="provenance"]').focus(); await page.keyboard.press('Space');
        assert.equal(await convert().isEnabled(), true);
        checks.independentProvenanceApproval = true;
        await convert().focus(); await page.keyboard.press('Enter');
        await panel().locator('[data-operation="restore"]').waitFor();
        checks.convertKeyboard = true;
        await page.reload();
        await panel().locator('[data-operation="restore"]').waitFor();
        checks.persistence = true;
        assert.equal(await panel().locator('.pixel-format-result').count(), 1);
        assert.equal(await panel().locator('.pixel-format-provenance').count(), 1);
        const result = await panel().locator('.pixel-format-result').innerText();
        assert.match(result, /PNG/); assert.match(result, /JPEG/); assert.match(result, /Gain sur/);
        assert.match(result, /%/); assert.match(result, /\d+\s*×\s*\d+/);
        checks.measuredFrenchComparison = true;
        for (const width of [1440, 820, 390, 320]) {
            await page.setViewportSize({width, height: 1100});
            assert.equal(await panel().evaluate(p => p.scrollWidth > p.clientWidth + 2), false);
            await panel().screenshot({path: path.join(out, `converted-${width}.png`)});
            checks['convertedWidth' + width] = true;
        }
        await page.setViewportSize({width: 1440, height: 2200});
        await page.evaluate(() => document.body.style.zoom = '2');
        await panel().evaluate(p => p.scrollIntoView({block: 'start'}));
        await page.evaluate(() => window.scrollBy(0, -100));
        assert.equal(await panel().evaluate(p => p.scrollWidth > p.clientWidth + 2), false);
        await panel().screenshot({path: path.join(out, 'converted-zoom200.png')});
        checks.convertedZoom200 = true;
        await page.evaluate(() => document.body.style.zoom = '');
        await panel().screenshot({path: path.join(out, 'converted.png')});
        await panel().locator('[data-operation="restore"]').click();
        await panel().locator('[data-operation="analyze"]').waitFor();
        checks.restore = true;
        assert.equal(await panel().locator('.pixel-format-result, .pixel-format-provenance').count(), 0);
        checks.noStaleRestoredComparison = true;
        const sourcePreview = await ctx.request.get('http://127.0.0.1:8877/wp-admin/admin-ajax.php?action=wp_seed_pixel_format_preview');
        assert.equal(sourcePreview.status(), 403); checks.previewCapabilityAndId = true;
        await page.goto(`http://127.0.0.1:8877/wp-admin/post.php?post=${state.override_id}&action=edit`);
        await panel().locator('[data-operation="analyze"]').click();
        await panel().locator('.pixel-format-comparison').waitFor();
        assert.equal(await panel().locator('[data-format-profile="good"]').isChecked(), true);
        assert.equal(await panel().locator('[data-format-approval="quality_override"]').count(), 0);
        checks.passingDefaultNoOverride = true;
        await panel().locator('[data-format-profile="web"]').focus(); await page.keyboard.press('Space');
        await panel().locator('[data-format-approval="quality_override"]').waitFor();
        assert.equal(await panel().locator('.pixel-format-comparison').getAttribute('open'), '');
        assert.match(await panel().locator('.pixel-format-quality-warning').innerText(), /Qualité non validée automatiquement/);
        await page.waitForFunction(() => [...document.querySelectorAll('.pixel-format-comparison img')].every(i => i.complete && i.naturalWidth > 0));
        checks.failingChoiceCompareOpen = true;
        await panel().locator('[data-format-approval="confirmed"]').check();
        await panel().locator('[data-format-approval="provenance"]').check();
        assert.equal(await convert().isDisabled(), true);
        checks.extraApprovalMandatory = true;
        await panel().locator('[data-format-approval="quality_override"]').focus(); await page.keyboard.press('Space');
        assert.equal(await convert().isEnabled(), true);
        await page.keyboard.press('Space');
        assert.equal(await convert().isDisabled(), true);
        checks.cancelOverride = true;
        for (const width of [1440, 820, 390, 320]) {
            await page.setViewportSize({width, height: 1100});
            assert.equal(await panel().evaluate(p => p.scrollWidth > p.clientWidth + 2), false);
            await panel().screenshot({path: path.join(out, `override-${width}.png`)});
            checks['overrideWidth' + width] = true;
        }
        await page.reload();
        assert.equal(await panel().locator('[data-format-profile="web"]').isChecked(), true);
        assert.equal(await panel().locator('[data-format-approval="quality_override"]').isChecked(), false);
        checks.reloadDoesNotApproveOverride = true;
        for (const name of ['confirmed', 'provenance', 'quality_override']) await panel().locator(`[data-format-approval="${name}"]`).check();
        await convert().focus(); await page.keyboard.press('Enter');
        await panel().locator('[data-operation="restore"]').waitFor();
        await page.reload();
        // Technical details stay collapsed, but contain durable quality/override evidence.
        assert.match(await panel().textContent(), /"quality_check":"FAIL"/);
        assert.match(await panel().textContent(), /"user_override":"Confirmed"/);
        assert.equal(await panel().locator('.pixel-format-result').count(), 1);
        checks.overridePersistedWithoutResultClutter = true;
        await panel().locator('[data-operation="restore"]').click();
        await panel().locator('[data-operation="analyze"]').waitFor();
        checks.restoreAfterOverride = true;
        assert.deepEqual(errors, []);
        checks.consoleErrors = true;
        fs.writeFileSync(path.join(out, 'browser.json'), JSON.stringify({checks, errors, count: Object.keys(checks).length}, null, 2));
        console.log(JSON.stringify({count: Object.keys(checks).length, errors: errors.length, status: 'PASS'}));
        await ctx.close();
    } finally { await browser.close(); }
})().catch(e => {console.error(e.message); process.exitCode = 1;});
