const {chromium} = require('playwright');
const {execFileSync} = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..'), report = path.join(root, 'reports/storage-m2');
const {command:php,args,file} = require('./local-php.cjs');
const phpRun = (name, ...extra) => JSON.parse(execFileSync(php, [...args, file(name), ...extra.map(String)], {encoding: 'utf8',windowsHide:true}));
const tool = (op, id = 0) => phpRun('jobs-tools.php', op, id);
const results = [];
const check = (name, ok) => { results.push({name, pass: Boolean(ok)}); if (!ok) throw Error(name); };
const base = 'http://127.0.0.1:8877';
let browser;
process.env.TEMP = process.env.TMP = path.join(root, '.runtime/browser-temp');
fs.mkdirSync(process.env.TEMP, {recursive: true});
(async () => {
    const before = phpRun('storage-browser-state.php');
    browser = await chromium.launch({channel: 'chrome', headless: true});
    for (const locale of ['en_US', 'fr_FR']) {
        const large = tool('create-large');
        const auth = phpRun('storage-browser-auth.php', locale);
        const context = await browser.newContext({locale: locale.replace('_', '-')});
        await context.addCookies(auth.cookies.map(cookie => ({...cookie, url: base, httpOnly: true, sameSite: 'Lax'})));
        const external = [], errors = [];
        await context.route('**/*', route => { if (new URL(route.request().url()).hostname !== '127.0.0.1') { external.push('external'); return route.abort(); } return route.continue(); });
        const page = await context.newPage(); page.on('pageerror', error => errors.push(error.message));
        await page.goto(base + '/wp-admin/upload.php?page=wp-seed-pixel-jobs');
        await page.locator('.pixel-job-item').first().waitFor();
        check(locale + ' translated heading', await page.locator('h1').innerText() === (locale === 'fr_FR' ? 'Simulation du stockage' : 'Storage simulation'));
        check(locale + ' CSS parses all rules', await page.evaluate(() => {
            const sheet = [...document.styleSheets].find(value => value.href?.includes('/assets/jobs.css'));
            return sheet && sheet.cssRules.length === 10 && sheet.cssRules[9].cssRules.length === 1;
        }));
        check(locale + ' 20-row pagination', await page.locator('.pixel-job-item').count() === 20);
        check(locale + ' reload has no automatic execution', tool('status', large.id).states.retained === undefined);
        await page.locator('#pixel-job-next').click(); await page.locator('#pixel-job-page').filter({hasText: '2 /'}).waitFor();
        check(locale + ' second page works', await page.locator('.pixel-job-item').count() === 20);
        await page.locator('#pixel-job-previous').click(); await page.locator('#pixel-job-page').filter({hasText: '1 /'}).waitFor();
        for (const width of [1440, 820, 390, 320]) {
            await page.setViewportSize({width, height: 1000});
            check(locale + ' ' + width + ' overflow absent', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
            await page.evaluate(() => scrollTo(0, 0));
            await page.screenshot({path: path.join(report, locale + '-' + width + '.png'), fullPage: true});
        }
        await page.setViewportSize({width: 1440, height: 1000});
        await page.locator('#pixel-job-resume').focus();
        check(locale + ' focus visible', await page.locator('#pixel-job-resume').evaluate(element => getComputedStyle(element).outlineStyle !== 'none'));
        await page.evaluate(() => { document.documentElement.style.zoom = '2'; });
        check(locale + ' zoom 200 overflow absent', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
        await page.screenshot({path: path.join(report, locale + '-zoom200.png'), fullPage: true});
        await page.evaluate(() => { document.documentElement.style.zoom = '1'; });
        await page.locator('#pixel-job-resume').focus(); await page.keyboard.press('Enter');
        await page.waitForFunction(() => document.querySelector('#pixel-job-progress').value === 2008);
        check(locale + ' keyboard resumes server state', tool('status', large.id).status === 'completed');
        check(locale + ' live announcement', await page.locator('#pixel-job-status').getAttribute('aria-live') === 'polite');
        const denied = await context.request.post(base + '/wp-admin/admin-ajax.php', {form: {action: 'wp_seed_pixel_jobs', operation: 'start', nonce: 'invalid', job_id: String(large.id)}});
        check(locale + ' nonce denied', denied.status() === 403);
        check(locale + ' non-POST rejected', (await context.request.get(base + '/wp-admin/admin-ajax.php', {params: {action: 'wp_seed_pixel_jobs', operation: 'status'}})).status() === 405);
        check(locale + ' no console errors', errors.length === 0);
        check(locale + ' no external traffic', external.length === 0);
        await context.close();
    }
    const anonymous = await browser.newContext();
    check('no anonymous route', (await anonymous.request.post(base + '/wp-admin/admin-ajax.php', {form: {action: 'wp_seed_pixel_jobs', operation: 'status'}})).status() === 400);
    await anonymous.close();
    tool('scan-small'); const small = tool('create');
    const auth = phpRun('storage-browser-auth.php', 'en_US');
    const context = await browser.newContext(); await context.addCookies(auth.cookies.map(cookie => ({...cookie, url: base, httpOnly: true, sameSite: 'Lax'})));
    await context.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
    const page = await context.newPage(); await page.goto(base + '/wp-admin/upload.php?page=wp-seed-pixel-jobs');
    await page.waitForFunction(() => !document.querySelector('#pixel-job-resume').disabled);
    check('running job can resume after browser closure', await page.locator('#pixel-job-resume').isEnabled());
    tool('pause', small.id); await page.reload(); await page.locator('#pixel-job-status').filter({hasText: 'Paused'}).waitFor();
    check('pause survives reload', tool('status', small.id).status === 'paused');
    await page.route('**/admin-ajax.php', async route => { if (new URLSearchParams(route.request().postData() || '').get('operation') === 'step') await new Promise(resolve => setTimeout(resolve, 300)); await route.continue(); });
    await page.locator('#pixel-job-resume').click();
    await page.waitForFunction(() => document.querySelector('#pixel-job-progress').value >= 1);
    await page.locator('#pixel-job-pause').click(); await page.locator('#pixel-job-status').filter({hasText: 'Paused'}).waitFor();
    check('browser pause at durable safe boundary', tool('status', small.id).status === 'paused');
    await page.locator('#pixel-job-cancel').click(); await page.locator('#pixel-job-status').filter({hasText: 'Cancelled'}).waitFor();
    check('cancel preserved completed work', tool('status', small.id).states.retained >= 1 && tool('status', small.id).status === 'cancelled');
    await page.locator('#pixel-job-build').click();
    await page.waitForFunction(() => !document.querySelector('#pixel-job-start').disabled);
    check('UI builds a frozen plan from M1', tool('status').kind === 'plan' && tool('status').status === 'completed');
    await page.locator('#pixel-job-start').click();
    await page.waitForFunction(() => document.querySelector('#pixel-job-progress').value === 3 && document.querySelector('#pixel-job-status').textContent.includes('Simulation #') && document.querySelector('#pixel-job-status').textContent.includes('Complete'));
    check('UI starts simulation from its completed plan', tool('status').kind === 'simulation' && tool('status').status === 'completed');
    const retry = tool('create'); tool('failed', retry.id); await page.reload(); await page.locator('#pixel-job-status').filter({hasText: 'Complete with errors'}).waitFor();
    await page.locator('#pixel-job-retry').click(); await page.locator('#pixel-job-status').filter({hasText: 'Paused'}).waitFor();
    check('UI retry requires explicit resume', tool('status', retry.id).status === 'paused');
    await page.locator('#pixel-job-resume').click(); await page.waitForFunction(() => document.querySelector('#pixel-job-progress').value === 3);
    check('UI retry completes', tool('status', retry.id).status === 'completed');
    let failed = 0;
    await page.route('**/admin-ajax.php', route => {
        if (new URLSearchParams(route.request().postData() || '').get('operation') === 'plan') { failed++; return route.fulfill({status: 503, contentType: 'application/json', body: JSON.stringify({success: false, data: {message: 'Synthetic request timeout'}})}); }
        return route.continue();
    });
    await page.locator('#pixel-job-build').click(); await page.locator('#pixel-job-error').filter({hasText: 'Synthetic request timeout'}).waitFor();
    check('request error visible with zero retries', failed === 1 && await page.locator('#pixel-job-error').getAttribute('role') === 'alert');
    await context.close();
    check('canonical media unchanged by browser simulation', phpRun('storage-browser-state.php').canonical_hash === before.canonical_hash);
    fs.writeFileSync(path.join(report, 'browser.json'), JSON.stringify({checks: results, passed: results.length, headless: true}, null, 2));
    process.stdout.write(JSON.stringify({passed: results.length}));
})().catch(error => { fs.writeFileSync(path.join(report, 'browser.json'), JSON.stringify({checks: results, failure: error.message}, null, 2)); process.stderr.write(error.stack); process.exitCode = 1; }).finally(async () => { if (browser) await browser.close(); });
