<?php
require __DIR__ . '/m3-runtime.php';
require_once ABSPATH . 'wp-admin/includes/image-edit.php';
global $wpdb;
$checks = array();
function ncheck($value, $name) { global $checks; $checks[$name] = (bool) $value; if (!$value) { throw new RuntimeException('FAIL ' . $name); } }
$id = m3_fixture('m3-detail.jpg', false); $path = get_attached_file($id); $i = getimagesize($path);
wp_update_attachment_metadata($id, array('file' => _wp_relative_upload_path($path), 'width' => $i[0], 'height' => $i[1], 'sizes' => array()));
$job = WP_Seed_Pixel_Jobs::replace_one($id, array('master' => 'replace_verified', 'dimensions' => 'max_edge', 'max_edge' => 1920), 1073741824)['id'];
WP_Seed_Pixel_Jobs::step($job);
ncheck(WP_Seed_Pixel_Jobs::status($job)['states']['retained'] === 1, 'native test master retained');
$before = hash_file('sha256', $path);
add_image_size('m3-future-size', 1200, 800, false);
wp_update_image_subsizes($id);
$meta = wp_get_attachment_metadata($id);
ncheck(isset($meta['sizes']['m3-future-size']) && $meta['sizes']['m3-future-size']['width'] === 1200, 'future native intermediate from retained master');
add_image_size('m3-too-large', 5000, 5000, false);
wp_update_image_subsizes($id);
ncheck(!isset(wp_get_attachment_metadata($id)['sizes']['m3-too-large']), 'native no upscale beyond retained resolution');
ncheck((bool) wp_get_attachment_image_srcset($id, 'full'), 'new native srcset coherent');
$editor = wp_get_image_editor($path); $result = $editor->crop(0, 0, 600, 400, 600, 400); $saved = $editor->save(WP_SEED_PIXEL_RECOVERY_ROOT . '/native-crop.jpg');
ncheck(!is_wp_error($result) && !is_wp_error($saved) && $saved['width'] === 600, 'native crop remains available');
unlink($saved['path']);
$editor = wp_get_image_editor($path); $rotated = $editor->rotate(90); $saved = $editor->save(WP_SEED_PIXEL_RECOVERY_ROOT . '/native-rotate.jpg');
ncheck(!is_wp_error($rotated) && !is_wp_error($saved) && $saved['width'] === 1280 && $saved['height'] === 1920, 'native rotate remains available');
unlink($saved['path']);
deactivate_plugins('wp-seed-pixel/wp-seed-pixel.php');
ncheck(hash_file('sha256', $path) === $before && (bool) wp_get_attachment_image($id, 'full'), 'Pixel deactivation no canonical change');
$route = rest_do_request(new WP_REST_Request('GET', '/wp/v2/media/' . $id));
ncheck($route->get_status() === 200 && $route->get_data()['source_url'] === wp_get_attachment_url($id), 'Pixel disabled REST native');
$list = wp_prepare_attachment_for_js($id);
ncheck(is_array($list) && $list['url'] === wp_get_attachment_url($id) && isset($list['sizes']['full']), 'Media Library native model');
activate_plugin('wp-seed-pixel/wp-seed-pixel.php');

$id = m3_fixture('m3-detail.jpg', false); $path = get_attached_file($id); $i = getimagesize($path);
wp_update_attachment_metadata($id, array('file' => _wp_relative_upload_path($path), 'width' => $i[0], 'height' => $i[1], 'sizes' => array()));
$gd_only = static function () { return array('WP_Image_Editor_GD'); };
add_filter('wp_image_editors', $gd_only);
$gd_before = WP_Seed_Pixel_Master_Adapter::snapshot($id);
$gd_job = WP_Seed_Pixel_Jobs::replace_one($id, array('master' => 'replace_verified', 'dimensions' => 'max_edge', 'max_edge' => 1920), 1073741824);
WP_Seed_Pixel_Jobs::step($gd_job['id']);
remove_filter('wp_image_editors', $gd_only);
ncheck(WP_Seed_Pixel_Jobs::status($gd_job['id'])['states']['retained'] === 1, 'GD-only RGB downsizing certified');
$gd_result = WP_Seed_Pixel_Jobs::results($gd_job['id'])['items'][0];
ncheck($gd_result['candidate']['backend'] === 'WP_Image_Editor_GD' && $gd_result['current_master']['width'] === 1920 && $gd_result['recovery_bytes'] === $gd_before['bytes'], 'bounded result exact backend dimensions and recovery bytes');
WP_Seed_Pixel_Jobs::restore_master($gd_job['id']);
ncheck(WP_Seed_Pixel_Master_Adapter::snapshot($id) === $gd_before, 'GD-only rollback exact');
ncheck(WP_Seed_Pixel_Jobs::results($gd_job['id'])['items'][0]['active_delta'] === 0, 'rollback result cannot claim historical candidate savings');

$id = m3_fixture('m3-color.jpg', false); $path = get_attached_file($id); $i = getimagesize($path);
wp_update_attachment_metadata($id, array('file' => _wp_relative_upload_path($path), 'width' => $i[0], 'height' => $i[1], 'sizes' => array()));
$profile = WP_Seed_Pixel_Color::inspect($path);
ncheck(WP_Seed_Pixel_Color::available(), 'Imagick LittleCMS capability actually available');
$gd_only = static function () { return array('WP_Image_Editor_GD'); };
add_filter('wp_image_editors', $gd_only);
$probe = WP_Seed_Pixel_Master_Processor::create($path, WP_SEED_PIXEL_RECOVERY_ROOT . '/unsafe-gd.jpg', WP_Seed_Pixel_Policy::normalize(array('master' => 'replace_verified')));
remove_filter('wp_image_editors', $gd_only);
ncheck(is_wp_error($probe) && $probe->get_error_code() === 'ICC_UNSAFE' && !file_exists(WP_SEED_PIXEL_RECOVERY_ROOT . '/unsafe-gd.jpg'), 'forced GD refuses ICC before encoding');
$j = WP_Seed_Pixel_Jobs::replace_one($id, array('master' => 'replace_verified'), 1073741824);
WP_Seed_Pixel_Jobs::step($j['id']);
ncheck(WP_Seed_Pixel_Jobs::status($j['id'])['states']['retained'] === 1, 'RGB ICC same-profile replacement retained');
ncheck(WP_Seed_Pixel_Color::inspect($path) === $profile, 'ICC preserved byte exact');
$out = dirname(__DIR__) . '/reports/storage-m3/visual'; wp_mkdir_p($out);
copy($path, $out . '/icc-after.jpg');
$item = $wpdb->get_row($wpdb->prepare('SELECT * FROM ' . WP_Seed_Pixel_Job_Store::table('items') . ' WHERE job_id=%d', $j['id']), ARRAY_A);
copy(WP_Seed_Pixel_Master_Storage::directory($item) . '/recovery.jpg', $out . '/icc-before.jpg');
WP_Seed_Pixel_Jobs::restore_master($j['id']);
ncheck(WP_Seed_Pixel_Color::inspect($path) === $profile, 'ICC rollback byte exact');
$id = m3_fixture('m3-p3.jpg', false); $path = get_attached_file($id); $i = getimagesize($path);
wp_update_attachment_metadata($id, array('file' => _wp_relative_upload_path($path), 'width' => $i[0], 'height' => $i[1], 'sizes' => array()));
$p3_before = WP_Seed_Pixel_Master_Adapter::snapshot($id); $profile = WP_Seed_Pixel_Color::inspect($path);
$p3_job = WP_Seed_Pixel_Jobs::replace_one($id, array('master' => 'replace_verified'), 1073741824); WP_Seed_Pixel_Jobs::step($p3_job['id']);
ncheck(!empty(WP_Seed_Pixel_Jobs::status($p3_job['id'])['states']['retained']) && WP_Seed_Pixel_Color::inspect($path) === $profile, 'Display P3 source pixels and exact source profile retained');
$item = $wpdb->get_row($wpdb->prepare('SELECT * FROM ' . WP_Seed_Pixel_Job_Store::table('items') . ' WHERE job_id=%d', $p3_job['id']), ARRAY_A);
copy($path, $out . '/p3-after.jpg'); copy(WP_Seed_Pixel_Master_Storage::directory($item) . '/recovery.jpg', $out . '/p3-before.jpg');
WP_Seed_Pixel_Jobs::restore_master($p3_job['id']);
ncheck(WP_Seed_Pixel_Master_Adapter::snapshot($id) === $p3_before, 'Display P3 exact rollback');
$id = m3_fixture('m3-detail.jpg', false); $path = get_attached_file($id); $i = getimagesize($path);
wp_update_attachment_metadata($id, array('file' => _wp_relative_upload_path($path), 'width' => $i[0], 'height' => $i[1], 'sizes' => array()));
$legacy = wp_seed_pixel_optimize($id, 'balanced');
ncheck(!is_wp_error($legacy) && $legacy['files']['view']['kind'] === 'derived', 'existing Pixel resources prepared through unchanged pipeline');
$legacy_manifest = WP_Seed_Pixel_Store::manifest($id);
$legacy_before = WP_Seed_Pixel_Master_Adapter::snapshot($id);
$legacy_job = WP_Seed_Pixel_Jobs::replace_one($id, array('master' => 'replace_verified'), 1073741824); WP_Seed_Pixel_Jobs::step($legacy_job['id']);
$legacy_status = WP_Seed_Pixel_Jobs::status($legacy_job['id']);
ncheck(!empty($legacy_status['states']['retained']), 'existing-resource replacement retained: ' . $legacy_status['error_code']);
ncheck(WP_Seed_Pixel_Store::manifest($id) === $legacy_manifest, 'replacement preserves existing Pixel manifest without new generation');
ncheck(!is_wp_error(wp_seed_pixel_get_derivative($id, 'view')) && !is_wp_error(wp_seed_pixel_get_derivative($id, 'thumb')), 'existing derivative getters remain valid');
WP_Seed_Pixel_Jobs::restore_master($legacy_job['id']);
ncheck(WP_Seed_Pixel_Master_Adapter::snapshot($id) === $legacy_before, 'existing resources exact scoped rollback');
foreach (array('m3-cmyk.jpg', 'm3-gray.jpg', 'm3-orientation.jpg') as $name) {
    $id = m3_fixture($name, false); $path = get_attached_file($id); $i = getimagesize($path);
    wp_update_attachment_metadata($id, array('file' => _wp_relative_upload_path($path), 'width' => $i[0], 'height' => $i[1], 'sizes' => array()));
    $sha = hash_file('sha256', $path); $j = WP_Seed_Pixel_Jobs::replace_one($id, array('master' => 'replace_verified'), 1073741824);
    if (!is_wp_error($j)) { WP_Seed_Pixel_Jobs::step($j['id']); }
    ncheck(hash_file('sha256', $path) === $sha && (is_wp_error($j) || empty(WP_Seed_Pixel_Jobs::status($j['id'])['states']['retained'])), "$name refused safely");
}
wp_mkdir_p(dirname(__DIR__) . '/reports/storage-m3');
file_put_contents(dirname(__DIR__) . '/reports/storage-m3/native.json', wp_json_encode(array('checks' => $checks, 'passed' => count($checks)), JSON_PRETTY_PRINT));
echo count($checks) . " native/ICC checks passed.\n";
