<?php
require __DIR__ . '/m4-runtime.php';
$checks = array(); $details = array();
list($id, $job, $view) = m4_replaced();
$item = m4_item($job); $dir = WP_Seed_Pixel_Master_Storage::directory($item);
$r = WP_Seed_Pixel_Quarantine::record($item); $master = get_attached_file($id); $sha = hash_file('sha256', $master);
m4_check($view['rollback_available'] && $view['quarantine_bytes'] === $r['before']['bytes'], 'verified quarantine');
m4_check($view['net_reclaimed_bytes'] < 0 && $view['removed_bytes'] === 0, 'same-disk quarantine not reclaimed');
m4_check(is_wp_error(WP_Seed_Pixel_Jobs::quarantine_action($job, 'purge')), 'purge explicit authorization required');
$sentinel = $dir . '/unrelated-sentinel'; file_put_contents($sentinel, 'do not remove');
$purged = WP_Seed_Pixel_Jobs::quarantine_action($job, 'purge', m4_approval($view));
m4_check(!is_wp_error($purged) && $purged['state'] === 'purged', 'purge recorded');
m4_check(!file_exists($dir . '/recovery.jpg') && m4_item($job)['stage'] === 'purged', 'file physically absent and SQL purged');
m4_check(hash_file('sha256', $master) === $sha && file_get_contents($sentinel) === 'do not remove', 'active and sentinel untouched');
m4_check(!$purged['rollback_available'] && $purged['removed_bytes'] === $view['source_bytes'], 'after purge restore unavailable actual removed bytes');
m4_check($purged['net_reclaimed_bytes'] === $purged['active_delta'] - $purged['audit_bytes'], 'purge net deducts audit');
m4_check(!is_wp_error(WP_Seed_Pixel_Jobs::quarantine_action($job, 'purge', m4_approval($view))), 'purge idempotent');
m4_check(is_wp_error(WP_Seed_Pixel_Jobs::quarantine_action($job, 'restore')), 'restore after purge refused');
m4_check(is_wp_error(WP_Seed_Pixel_Jobs::restore_master($job)), 'old restore route cannot bypass purge');
$details['master_purge'] = array('quarantine' => $view, 'purge' => $purged);

list($id, $job, $view) = m4_replaced(); $item = m4_item($job); $r = WP_Seed_Pixel_Quarantine::record($item);
$restored = WP_Seed_Pixel_Jobs::quarantine_action($job, 'restore');
m4_check(!is_wp_error($restored) && $restored['state'] === 'restored', 'M3 source restored through M4');
m4_check(WP_Seed_Pixel_Master_Adapter::snapshot($id) === $r['before'], 'exact bytes native metadata restored');
m4_check($restored['quarantine_bytes'] === 0 && $restored['active_delta'] === 0, 'no duplicate source after restore');
m4_check(!is_wp_error(WP_Seed_Pixel_Jobs::quarantine_action($job, 'restore')), 'restore idempotent');
$again = WP_Seed_Pixel_Jobs::replace_one($id, array('master' => 'replace_verified'), 1073741824); WP_Seed_Pixel_Jobs::step($again['id']);
$new_sha = hash_file('sha256', get_attached_file($id));
m4_check(is_wp_error(WP_Seed_Pixel_Jobs::quarantine_action($job, 'purge', m4_approval($view))) && hash_file('sha256', get_attached_file($id)) === $new_sha, 'old generation cannot purge new master');

list($id, $job) = m4_original(); $before = WP_Seed_Pixel_Master_Adapter::snapshot($id);
$original = wp_get_original_image_path($id); $original_sha = hash_file('sha256', $original); $master = get_attached_file($id); $master_sha = hash_file('sha256', $master);
$srcset = wp_get_attachment_image_srcset($id, 'full'); $url = wp_get_attachment_url($id);
WP_Seed_Pixel_Jobs::step($job); $item = m4_item($job);
m4_check($item['stage'] === 'retained', 'big-image quarantine retained ' . $item['error_code']);
$view = WP_Seed_Pixel_Quarantine::inspect($item);
m4_check(!file_exists($original) && !isset(wp_get_attachment_metadata($id)['original_image']), 'original absent no dangling original_image');
m4_check(wp_get_original_image_path($id) === $master && hash_file('sha256', $master) === $master_sha, 'native fallback operational bytes unchanged');
m4_check(wp_get_attachment_url($id) === $url && wp_get_attachment_image_srcset($id, 'full') === $srcset, 'URL srcset unchanged');
m4_check($view['net_reclaimed_bytes'] === -$view['audit_bytes'] && $view['removed_bytes'] === 0, 'moving original frees no same-disk source bytes');
$restored = WP_Seed_Pixel_Jobs::quarantine_action($job, 'restore');
m4_check(!is_wp_error($restored) && hash_file('sha256', $original) === $original_sha, 'big-image original restore exact');
m4_check(WP_Seed_Pixel_Master_Adapter::snapshot($id) === $before, 'big-image exact relationship restoration');
$again = WP_Seed_Pixel_Jobs::retire_original($id, 1073741824, true); WP_Seed_Pixel_Jobs::step($again['id']);
$view = WP_Seed_Pixel_Quarantine::inspect(m4_item($again['id']));
$purged = WP_Seed_Pixel_Jobs::quarantine_action($again['id'], 'purge', m4_approval($view));
m4_check(!is_wp_error($purged) && $purged['kind'] === 'preserved_original' && $purged['removed_bytes'] === $view['source_bytes'], 'original purge separate category');
m4_check(!file_exists($original) && hash_file('sha256', $master) === $master_sha, 'original purge leaves active exact');
add_image_size('m4-new', 1100, 1100, false); add_image_size('m4-too-large', 6000, 6000, false);
wp_update_image_subsizes($id); $meta = wp_get_attachment_metadata($id);
m4_check(isset($meta['sizes']['m4-new']) && !isset($meta['sizes']['m4-too-large']), 'future native size retained resolution no upscale');
$response = rest_do_request(new WP_REST_Request('GET', '/wp/v2/media/' . $id));
m4_check($response->get_status() === 200 && $response->get_data()['source_url'] === $url, 'REST after original purge');
$editor = wp_get_image_editor($master); $crop = $editor->crop(0, 0, 300, 300); $tmp = WP_SEED_PIXEL_RECOVERY_ROOT . '/m4-edit.jpg'; $save = $editor->save($tmp);
m4_check(!is_wp_error($crop) && !is_wp_error($save), 'native crop from retained master');
unlink($tmp);
$details['original'] = array('attachment_id' => $id, 'job' => $again['id'], 'view' => $view, 'purged' => $purged, 'master_sha' => $master_sha, 'url' => $url);
update_option('pixel_m4_native_fixture', $id, false);
m4_report('integration', $details);
