<?php
require __DIR__ . '/m5-support.php'; global $wpdb; $checks = array();
$wpdb->query("UPDATE {$wpdb->posts} SET post_status='trash' WHERE post_type='attachment'"); wp_cache_flush();
$ids = array(m5_image(), m5_image()); $sha = hash_file('sha256', get_attached_file($ids[0]));
$plan = m5_plan(); $job = m5_result(WP_Seed_Pixel_Jobs::start($plan['id'])); $id = (int) $job['id'];
$none = static function () { return array(); }; add_filter('wp_image_editors', $none);
m5_result(WP_Seed_Pixel_Jobs::bulk_step($id)); remove_filter('wp_image_editors', $none);
$item = m5_items($id)[0]; $dir = WP_Seed_Pixel_Master_Storage::directory($item, false);
$journal = file_get_contents($dir . '/journal.json');
$a = m5_result(WP_Seed_Pixel_Jobs::storage_audit($id));
m5_assert($a['complete'] && $a['temporary_bytes'] > 0 && $a['net_reclaimed_bytes'] < 0, 'failed escrow is measured without fictional saving');
file_put_contents($dir . '/foreign.txt', 'synthetic foreign evidence');
$a = m5_result(WP_Seed_Pixel_Jobs::storage_audit($id));
m5_assert(!$a['complete'] && $a['net_reclaimed_bytes'] === null && $a['quarantine_bytes'] === null, 'foreign pending file suppresses uncertain totals');
m5_assert(file_exists($dir . '/foreign.txt'), 'read-only audit never deletes a foreign file'); unlink($dir . '/foreign.txt');
link($dir . '/recovery.jpg', $dir . '/hardlink.jpg');
$a = m5_result(WP_Seed_Pixel_Jobs::storage_audit($id));
m5_assert(!$a['complete'] && $a['temporary_bytes'] === null, 'linked pending escrow cannot create a trusted physical total'); unlink($dir . '/hardlink.jpg');
$r = json_decode($journal, true); $r['checksum'] = str_repeat('0', 64); file_put_contents($dir . '/journal.json', wp_json_encode($r));
$a = m5_result(WP_Seed_Pixel_Jobs::storage_audit($id));
m5_assert(!$a['complete'] && $a['current_active_bytes'] === null, 'corrupt journal cannot produce a complete active subtotal');
m5_assert(file_get_contents($dir . '/journal.json') === wp_json_encode($r), 'audit does not rewrite corrupt evidence');
file_put_contents($dir . '/journal.json', $journal);
m5_assert(hash_file('sha256', get_attached_file($ids[0])) === $sha, 'accounting attacks leave canonical source exact');
m5_result(WP_Seed_Pixel_Jobs::control($id, 'retry')); m5_result(WP_Seed_Pixel_Jobs::control($id, 'resume')); m5_finish($id);
$a = m5_result(WP_Seed_Pixel_Jobs::storage_audit($id));
m5_assert($a['complete'] && $a['net_reclaimed_bytes'] === $a['active_saved_bytes'] - $a['quarantine_bytes'] - $a['audit_bytes'] - $a['temporary_bytes'], 'healthy resumed totals reconcile exact net overhead');
m5_assert($a['removed_source_bytes'] === 0, 'no purge or reclaimed receipt invented by audit');
m5_report('accounting-unknown', array('audit' => $a));
