const {chromium} = require('playwright');
const {execFileSync} = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const report = path.join(root, 'reports/storage-m1');
const {command:php,args,file} = require('./local-php.cjs');
const results = [];
const check = (name, ok) => { results.push({name, pass: Boolean(ok)}); if (!ok) throw Error(name); };
const base = 'http://127.0.0.1:8877';
let browser;
process.env.TEMP = process.env.TMP = path.join(root, '.runtime/browser-temp');
fs.mkdirSync(process.env.TEMP, {recursive: true});
(async () => {
    const snapshot = () => JSON.parse(execFileSync(php, [...args, file('storage-browser-state.php')], {encoding: 'utf8',windowsHide:true}));
    const canonicalBefore = snapshot();
    browser = await chromium.launch({channel: 'chrome', headless: true});
    for (const locale of ['en_US', 'fr_FR']) {
        const auth = JSON.parse(execFileSync(php, [...args, file('storage-browser-auth.php'), locale], {encoding: 'utf8',windowsHide:true}));
        const context = await browser.newContext({locale: locale.replace('_', '-')});
        await context.addCookies(auth.cookies.map(cookie => ({...cookie, url: base, httpOnly: true, sameSite: 'Lax'})));
        const external = [], errors = [];
        await context.route('**/*', route => { if (new URL(route.request().url()).hostname !== '127.0.0.1') { external.push(new URL(route.request().url()).hostname); return route.abort(); } return route.continue(); });
        const page = await context.newPage();
        page.on('pageerror', error => errors.push(error.message));
        await page.goto(base + '/wp-admin/upload.php?page=wp-seed-pixel-storage');
        await page.locator('.pixel-scan-item').first().waitFor();
        check(locale + ' stylesheet parses completely', await page.evaluate(() => {
            const sheet = [...document.styleSheets].find(value => value.href && value.href.endsWith('storage.css?ver=1'));
            return Boolean(sheet && sheet.cssRules.length === 16 && sheet.cssRules[14].cssRules.length === 1 && sheet.cssRules[15].cssRules.length === 1);
        }));
        check(locale + ' heading translated', (await page.locator('h1').innerText()) === (locale === 'fr_FR' ? 'Stockage des images' : 'Image storage'));
        check(locale + ' zero reclaimed', (await page.locator('#pixel-scan-reclaimed').innerText()).includes('0'));
        check(locale + ' pagination bounded', await page.locator('.pixel-scan-item').count() === 20);
        check(locale + ' real native previews', await page.locator('.pixel-scan-item img').count() > 0);
        const before = await page.locator('#pixel-scan-status').innerText();
        await page.reload(); await page.locator('.pixel-scan-item').first().waitFor();
        check(locale + ' reload does not start processing', await page.locator('#pixel-scan-status').innerText() === before);
        await page.locator('#pixel-scan-next').click();
        await page.locator('#pixel-scan-page').filter({hasText: '2 /'}).waitFor();
        check(locale + ' next page works', await page.locator('.pixel-scan-item').count() === 20);
        await page.locator('#pixel-scan-filter').selectOption('missing');
        await page.locator('.pixel-scan-item').filter({hasText: 'm1-missing'}).waitFor();
        check(locale + ' filter works', await page.locator('.pixel-scan-item').count() === 1);
        await page.locator('#pixel-scan-filter').selectOption('');
        await page.waitForFunction(() => document.querySelectorAll('.pixel-scan-item').length === 20);
        for (const width of [1440, 820, 390, 320]) {
            await page.setViewportSize({width, height: 1000});
            check(locale + ' ' + width + ' no overflow', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
            await page.evaluate(() => scrollTo(0, 0));
            await page.screenshot({path: path.join(report, locale + '-' + width + '.png'), fullPage: true});
        }
        await page.setViewportSize({width: 1440, height: 1000});
        await page.locator('#pixel-scan-filter').focus();
        check(locale + ' keyboard focus visible', await page.locator('#pixel-scan-filter').evaluate(element => getComputedStyle(element).outlineStyle !== 'none'));
        await page.locator('.pixel-scan-item details summary').first().focus();
        await page.keyboard.press('Enter');
        check(locale + ' keyboard details', await page.locator('.pixel-scan-item details').first().getAttribute('open') !== null);
        await page.evaluate(() => { document.documentElement.style.zoom = '2'; });
        check(locale + ' 200 percent overflow', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
        await page.evaluate(() => scrollTo(0, 0));
        await page.screenshot({path: path.join(report, locale + '-zoom200.png'), fullPage: true});
        const denied = await context.request.post(base + '/wp-admin/admin-ajax.php', {form: {action: 'wp_seed_pixel_scan', operation: 'start', nonce: 'invalid'}});
        check(locale + ' invalid nonce denied', denied.status() === 403);
        check(locale + ' console errors zero', errors.length === 0);
        check(locale + ' external requests zero', external.length === 0);
        await context.close();
    }
    const anonymous = await browser.newContext();
    check('anonymous no public scan route', (await anonymous.request.post(base + '/wp-admin/admin-ajax.php', {form: {action: 'wp_seed_pixel_scan', operation: 'status'}})).status() === 400);
    await anonymous.close();
    const auth = JSON.parse(execFileSync(php, [...args, file('storage-browser-auth.php'), 'en_US'], {encoding: 'utf8',windowsHide:true}));
    const controls = await browser.newContext();
    await controls.addCookies(auth.cookies.map(cookie => ({...cookie, url: base, httpOnly: true, sameSite: 'Lax'})));
    await controls.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
    const page = await controls.newPage();
    await page.goto(base + '/wp-admin/upload.php?page=wp-seed-pixel-storage');
    await page.locator('#pixel-scan-start').waitFor({state: 'visible'});
    await page.locator('#pixel-scan-start').click();
    await page.waitForFunction(() => document.querySelector('#pixel-scan-progress').value > 0);
    await page.locator('#pixel-scan-pause').click();
    await page.locator('#pixel-scan-status').filter({hasText: 'Paused'}).waitFor();
    const paused = await page.locator('#pixel-scan-progress').getAttribute('value');
    await page.reload();
    await page.locator('#pixel-scan-status').filter({hasText: 'Paused'}).waitFor();
    check('pause persists after reload', await page.locator('#pixel-scan-progress').getAttribute('value') === paused);
    await page.locator('#pixel-scan-resume').click();
    await page.waitForFunction(value => document.querySelector('#pixel-scan-progress').value > Number(value), paused);
    check('explicit resume advances cursor', true);
    await page.locator('#pixel-scan-cancel').click();
    await page.locator('#pixel-scan-status').filter({hasText: 'Cancelled'}).waitFor();
    await page.reload();
    await page.locator('#pixel-scan-status').filter({hasText: 'Cancelled'}).waitFor();
    check('cancel persists after reload', true);
    let failedStarts = 0;
    await page.route('**/admin-ajax.php', route => {
        const operation = new URLSearchParams(route.request().postData() || '').get('operation');
        if (operation === 'start') { failedStarts++; return route.fulfill({status: 503, contentType: 'application/json', body: JSON.stringify({success: false, data: {message: 'Synthetic transport failure'}})}); }
        return route.continue();
    });
    await page.locator('#pixel-scan-start').click();
    await page.locator('#pixel-scan-status').filter({hasText: 'Synthetic transport failure'}).waitFor();
    check('failure remains visible with no retry', failedStarts === 1);
    await controls.close();
    check('browser controls leave canonical media unchanged', snapshot().canonical_hash === canonicalBefore.canonical_hash);
    fs.writeFileSync(path.join(report, 'browser.json'), JSON.stringify({checks: results, pass: results.every(result => result.pass)}, null, 2));
    process.stdout.write(JSON.stringify({passed: results.length, headless: true, visibleChromeUsed: false}));
})().catch(error => { fs.writeFileSync(path.join(report, 'browser.json'), JSON.stringify({checks: results, failure: error.message}, null, 2)); process.stderr.write(error.stack); process.exitCode = 1; }).finally(async () => { if (browser) await browser.close(); });
