"""Generate standard gettext catalogues and the presentation-only message inventory."""
from pathlib import Path
import gettext
import io
import json
import re
import struct

ROOT = Path(__file__).resolve().parents[1]
DOMAIN = 'wp-seed-pixel'
translations = json.loads((ROOT / 'tools/i18n-fr.json').read_text(encoding='utf-8'))
literal = r"'((?:\\.|[^'\\])*)'"
messages, plural, evidence = set(), {}, set()
for file in sorted((ROOT / 'includes').glob('*.php')):
    if file.name == 'i18n-messages.php':
        continue
    source = file.read_text(encoding='utf-8')
    for m in re.finditer(r'(?:__|_e|esc_html__|esc_html_e|esc_attr__|esc_attr_e)\(\s*' + literal + r"\s*,\s*'wp-seed-pixel'", source):
        messages.add(m[1])
    for m in re.finditer(r'_n\(\s*' + literal + r'\s*,\s*' + literal, source):
        messages.add(m[1]); plural[m[1]] = m[2]
    for m in re.finditer(r'new\s+WP_Error\(\s*' + literal + r'\s*,\s*' + literal, source):
        evidence.add(m[2])
evidence |= {m for m in translations if m in {
    'Fixed profile', 'Unsupported format or explicit exclusion.',
    'Explicit legacy/custom fixed preset.',
    'Metadata/orientation sanitization required; byte increase disclosed.',
    'Metric unavailable: conservative fixed Q94 fallback.',
    'First bounded candidate satisfying local quality and byte gates.',
    'Source already bounded, light and metadata-safe.',
    'No material byte saving at the quality floor; source retained.',
    'No candidate meets the quality floor; source retained, dimension target may be exceeded.'}}
messages |= evidence
missing = sorted(messages - translations.keys())
if missing:
    raise ValueError('Missing French translations: ' + json.dumps(missing))
quote = lambda s: json.dumps(s, ensure_ascii=False)
header = 'Project-Id-Version: WP Seed Pixel 0.4.0\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\nLanguage: fr_FR\nPlural-Forms: nplurals=2; plural=(n > 1);\nX-Domain: wp-seed-pixel\n'
po = ['msgid ""\nmsgstr ' + quote(header) + '\n']
pot = ['msgid ""\nmsgstr ' + quote(header.replace('Language: fr_FR\n', 'Language: \n').replace('plural=(n > 1);', 'plural=(n != 1);')) + '\n']
mo = {'': header}
placeholder = re.compile(r'%(?:[1-9][0-9]*\$)?[dsf]')
for message in sorted(messages):
    value = translations[message]
    values = value if isinstance(value, list) else [value]
    for translated in values:
        if sorted(placeholder.findall(message)) != sorted(placeholder.findall(translated)):
            raise ValueError('Placeholder mismatch: ' + message)
    block = 'msgid ' + quote(message) + '\n'
    if message in plural:
        if len(values) != 2:
            raise ValueError('Two plural translations required')
        block += 'msgid_plural ' + quote(plural[message]) + '\n'
        po.append(block + '\n'.join('msgstr[%d] %s' % (i, quote(v)) for i, v in enumerate(values)) + '\n')
        pot.append(block + 'msgstr[0] ""\nmsgstr[1] ""\n')
        mo[message + '\0' + plural[message]] = '\0'.join(values)
    else:
        po.append(block + 'msgstr ' + quote(value) + '\n')
        pot.append(block + 'msgstr ""\n')
        mo[message] = value
keys = sorted(mo)
originals = [k.encode('utf-8') for k in keys]
translated = [mo[k].encode('utf-8') for k in keys]
n = len(keys); start = 28 + n * 16
left = b'\0'.join(originals) + b'\0'; right = b'\0'.join(translated) + b'\0'
tables = []
for strings, offset in [(originals, start), (translated, start + len(left))]:
    table = b''
    for s in strings:
        table += struct.pack('<II', len(s), offset); offset += len(s) + 1
    tables.append(table)
binary = struct.pack('<7I', 0x950412de, 0, n, 28, 28 + n * 8, 0, 0) + b''.join(tables) + left + right
catalogue = gettext.GNUTranslations(io.BytesIO(binary))
for message in messages:
    if message in plural:
        assert catalogue.ngettext(message, plural[message], 1) == translations[message][0]
        assert catalogue.ngettext(message, plural[message], 2) == translations[message][1]
    else:
        assert catalogue.gettext(message) == translations[message]
language = ROOT / 'languages'; language.mkdir(exist_ok=True)
(language / 'wp-seed-pixel-fr_FR.po').write_text('\n'.join(po), encoding='utf-8', newline='\n')
(language / 'wp-seed-pixel.pot').write_text('\n'.join(pot), encoding='utf-8', newline='\n')
(language / 'wp-seed-pixel-fr_FR.mo').write_bytes(binary)
php = "<?php\ndefined('ABSPATH') || exit;\n// Generated by tools/i18n.py; engine strings and stored evidence are not changed.\nreturn array(\n"
escape = lambda s: s.replace('\\', '\\\\').replace("'", "\\'")
for message in sorted(evidence):
    s = escape(message)
    php += "    '%s' => __('%s', 'wp-seed-pixel'),\n" % (s, s)
php += ');\n'
(ROOT / 'includes/i18n-messages.php').write_text(php, encoding='utf-8', newline='\n')
print(json.dumps({'messages': len(messages), 'engineMessagesAtPresentationOnly': len(evidence), 'missing': 0, 'MOChecks': 'PASS', 'plurals': len(plural)}))
